version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=goSentinel
      - POSTGRES_USER=goSentinel
      - POSTGRES_PASSWORD=password
    ports:
      - '5425:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local